### ISSUE TITLE
Images are not displayed (medias, avatars...)

### ISSUE THREAD

**Issue by ae3e** [fedify-dev/hollo#133]
Which URL should I use for `STORAGE_URL_BASE` with `DRIVE_DISK: fs`? Why is this parameter needed for local storage?

Currently, files are well written in the media folder of the volume outside the docker container but links (ie https://mymicroblog.xxxx/media/01958ae9-d6e9-7519-b204-bc5abc60ddde/thumbnail.webp) return 404 errors.

I tried both local and public URL with the `ghcr.io/fedify-dev/hollo:canary` image

Thanks for your help

**Comment by ThisIsMissEm** [comment]
It's because we need to publish absolute URLs to media, and need to know where they are on the web.

I'm not sure on your specific setup, for me in development I have these set:
```
DRIVE_DISK=fs
STORAGE_URL_BASE=http://hollo.local/
FS_STORAGE_PATH=assets/
```

**Comment by ae3e** [comment]
Thanks for your quick answer... and sorry to borrow you. Finally, I think the integrated reverse proxy of my NAS was the culprit. Everything works fine after a reboot.

Here is my full complete `compose.yaml` file if it can help someone else :

```yaml
services:
  hollo:
    container_name: hollo
    image: ghcr.io/fedify-dev/hollo:canary
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: "postgres://user:password@host:5432/hollo"
      SECRET_KEY: "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
      LOG_LEVEL: "debug"
      BEHIND_PROXY: "true"
      DRIVE_DISK: fs
      FS_STORAGE_PATH: /var/lib/hollo/
      STORAGE_URL_BASE: https://microblog.mydomain.com/
    volumes:
      - /volume1/docker/hollo:/var/lib/hollo/
 ```
